// apps/diagnosis-app/src/components/layout/AppFooter.tsx
import { COPYRIGHT, FOOTER_NAV_ITEMS } from '@corporate-estimate/shared';
import styles from './AppFooter.module.scss';

const PUBLIC_SITE_ORIGIN =
  process.env.NEXT_PUBLIC_PUBLIC_SITE_ORIGIN
  || (process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : '');

export function AppFooter() {
  return (
    <footer className={styles['footer']}>
      <div className={styles['footer__inner']}>
        <nav className={styles['footer__nav']}>
          <ul className={styles['footer__nav-list']}>
            {FOOTER_NAV_ITEMS.map((item) => (
              <li key={item.href} className={styles['footer__nav-item']}>
                <a
                  href={`${PUBLIC_SITE_ORIGIN}${item.href}`}
                  className={styles['footer__nav-link']}
                >
                  {item.label}
                </a>
              </li>
            ))}
          </ul>
        </nav>
        <p className={styles['footer__copyright']}>{COPYRIGHT}</p>
      </div>
    </footer>
  );
}

// apps/public-site/components/AppFooter.vue
<template>
  <footer class="footer">
    <div class="footer__inner">
      <nav class="footer__nav">
        <ul class="footer__nav-list">
          <li v-for="item in navItems" :key="item.href" class="footer__nav-item">
            <NuxtLink :to="item.href" class="footer__nav-link">
              {{ item.label }}
            </NuxtLink>
          </li>
        </ul>
      </nav>
      <p class="footer__copyright">{{ copyright }}</p>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { COPYRIGHT, FOOTER_NAV_ITEMS } from '@corporate-estimate/shared';

const copyright = COPYRIGHT;
const navItems = FOOTER_NAV_ITEMS;
</script>

<style lang="scss" scoped>
.footer {
  background-color: var(--color-bg-light);
  border-top: 1px solid var(--color-border);
  padding: $spacing-xl 0;

  &__inner {
    @include container;
    text-align: center;
  }

  &__nav-list {
    display: flex;
    justify-content: center;
    gap: $spacing-lg;
    list-style: none;
    margin-bottom: $spacing-md;
  }

  &__nav-link {
    font-size: $font-size-sm;
    color: var(--color-text-light);
    text-decoration: none;
    transition: color $transition-base;

    &:hover {
      color: var(--color-primary);
    }
  }

  &__copyright {
    font-size: $font-size-xs;
    color: var(--color-text-light);
  }
}
</style>
